# Generated by Django 5.1.4 on 2024-12-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedata',
            name='price',
            field=models.IntegerField(),
        ),
    ]
